"""
Script to update leagues.json with licensing flags and real league names,
and add real sponsors to teams_eu.json and teams_br.json.
"""
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEEDS = os.path.join(BASE, "data", "seeds")

# ═══════════════════════════════════════════════════════════
#  REAL LEAGUE NAMES PER COUNTRY (for generic ones)
# ═══════════════════════════════════════════════════════════

REAL_LEAGUE_NAMES = {
    "AFG": {1: "Afghan Premier League", 2: "Afghan 2nd Division", 3: "Afghan 3rd Division", 4: "Afghan 4th Division"},
    "AFS": {1: "Premier Soccer League", 2: "National First Division", 3: "ABC Motsepe League", 4: "SAB League"},
    "AGO": {1: "Girabola", 2: "Segunda Divisão", 3: "Terceira Divisão", 4: "Quarta Divisão"},
    "AIA": {1: "AFA Senior League"},
    "ALB": {1: "Kategoria Superiore", 2: "Kategoria e Parë", 3: "Kategoria e Dytë", 4: "Kategoria e Tretë"},
    "ALG": {1: "Ligue 1 Mobilis", 2: "Ligue 2 Mobilis", 3: "Division Nationale Amateur", 4: "Inter-Régions"},
    "AND": {1: "Primera Divisió", 2: "Segona Divisió"},
    "ARM": {1: "Armenian Premier League", 2: "Armenian First League"},
    "ARS": {1: "Saudi Pro League", 2: "Saudi First Division", 3: "Saudi Second Division", 4: "Saudi Third Division"},
    "ARU": {1: "Aruba Division di Honor"},
    "ATG": {1: "ABFA Premier Division"},
    "AUS": {1: "A-League Men", 2: "National Premier Leagues", 3: "NPL 2", 4: "NPL 3"},
    "AZE": {1: "Premyer Liqa", 2: "Birinci Dəstə"},
    "BAH": {1: "BFA Senior League"},
    "BAN": {1: "Bangladesh Premier League", 2: "Bangladesh Championship League"},
    "BAR": {1: "BFA Premier League"},
    "BEL": {1: "Pro League", 2: "Challenger Pro League", 3: "Nationale 1", 4: "Reserve Pro League 2A"},
    "BEN": {1: "Championnat National du Bénin"},
    "BER": {1: "Bermuda Premier Division"},
    "BHR": {1: "Bahraini Premier League"},
    "BIE": {1: "Belarusian Premier League", 2: "Belarusian First League"},
    "BKF": {1: "Burkinabè Premier League"},
    "BLZ": {1: "Premier League of Belize"},
    "BOL": {1: "División Profesional", 2: "Copa Simón Bolívar", 3: "Liga Municipal", 4: "Liga Regional"},
    "BON": {1: "Bonaire League"},
    "BOS": {1: "Premijer Liga BiH", 2: "Prva Liga FBiH", 3: "Prva Liga RS"},
    "BOT": {1: "Botswana Premier League"},
    "BRU": {1: "Brunei Super League"},
    "BUL": {1: "First Professional League", 2: "Second Professional League"},
    "BUR": {1: "Ligue 1 du Burundi"},
    "BUT": {1: "Bhutan A-Division"},
    "CAM": {1: "Ligue 1 du Cameroun", 2: "Ligue 2 du Cameroun"},
    "CAN": {1: "Canadian Premier League", 2: "League1 Canada"},
    "CAT": {1: "Qatar Stars League", 2: "Qatar Second Division"},
    "CAV": {1: "Cape Verdean Football Championship"},
    "CAZ": {1: "Kazakhstan Premier League", 2: "Kazakhstan First Division"},
    "CHA": {1: "Championnat du Tchad"},
    "CHI": {1: "Primera División", 2: "Primera B", 3: "Segunda División", 4: "Tercera División"},
    "CHN": {1: "Chinese Super League", 2: "China League One", 3: "China League Two", 4: "China Amateur League"},
    "CMJ": {1: "J1 League", 2: "J2 League", 3: "J3 League"},
    "CNG": {1: "Linafoot", 2: "Division 2"},
    "COL": {1: "Liga BetPlay", 2: "Torneo BetPlay", 3: "Liga Colombiana 3", 4: "Liga Colombiana 4"},
    "COM": {1: "Comoros Premier League"},
    "CPR": {1: "Cypriot First Division", 2: "Cypriot Second Division"},
    "CRN": {1: "Championnat du Congo Brazzaville"},
    "CRO": {1: "Hrvatska Nogometna Liga", 2: "Prva NL", 3: "Druga NL", 4: "Treća NL"},
    "CRS": {1: "Costa Rican Primera División", 2: "Liga de Ascenso"},
    "CUB": {1: "Campeonato Nacional de Cuba"},
    "CUR": {1: "Curaçao Sekshon Pagá"},
    "DIN": {1: "Superligaen", 2: "NordicBet Liga", 3: "Danmarksserien", 4: "Kvalifikationsserien"},
    "DJI": {1: "Djibouti Premier League"},
    "DOM": {1: "Liga Dominicana de Fútbol"},
    "EGI": {1: "Egyptian Premier League", 2: "Egyptian Second Division"},
    "ELQ": {1: "Ecuadorian Serie A"},
    "ELS": {1: "Primera División de El Salvador"},
    "EMI": {1: "UAE Pro League", 2: "UAE First Division", 3: "UAE Second Division", 4: "UAE Third Division"},
    "EQU": {1: "LigaPro Serie A", 2: "LigaPro Serie B", 3: "Segunda Categoría", 4: "Tercera Categoría"},
    "ERI": {1: "Eritrean Premier League"},
    "ESC": {1: "Scottish Premiership", 2: "Scottish Championship", 3: "Scottish League One", 4: "Scottish League Two"},
    "ESS": {1: "Eswatini Premier League"},
    "EST": {1: "Meistriliiga", 2: "Esiliiga"},
    "ESV": {1: "Slovenian PrvaLiga", 2: "Slovenian 2.SNL"},
    "ETI": {1: "Ethiopian Premier League"},
    "FIJ": {1: "Fiji Premier League"},
    "FIL": {1: "Philippines Football League"},
    "FIN": {1: "Veikkausliiga", 2: "Ykkönen"},
    "GAB": {1: "Championnat du Gabon"},
    "GAM": {1: "GFF League First Division"},
    "GAN": {1: "Ghana Premier League", 2: "Ghana Division One League"},
    "GDA": {1: "Championnat National du Guadeloupe"},
    "GEO": {1: "Erovnuli Liga", 2: "Erovnuli Liga 2"},
    "GFR": {1: "Championnat de Guyane"},
    "GIB": {1: "Gibraltar National League"},
    "GMA": {1: "Championnat de Guam"},
    "GNB": {1: "Campeonato da Guiné-Bissau"},
    "GNE": {1: "Liga Nacional de Guinea Ecuatorial"},
    "GRA": {1: "Grenada Premier League"},
    "GUA": {1: "Liga Nacional de Guatemala"},
    "GUI": {1: "Ligue 1 Guinéenne"},
    "GUN": {1: "Championnat de la Guinée"},
    "HAI": {1: "Ligue Haïtienne"},
    "HKG": {1: "Hong Kong Premier League"},
    "HON": {1: "Liga Nacional de Honduras"},
    "HUN": {1: "Nemzeti Bajnokság I", 2: "Nemzeti Bajnokság II"},
    "ICA": {1: "Íslenska úrvalsdeild karla"},
    "ICM": {1: "Cayman Islands Football League"},
    "ICO": {1: "K League 1", 2: "K League 2", 3: "K3 League", 4: "K4 League"},
    "IDO": {1: "Liga 1 Indonesia", 2: "Liga 2 Indonesia"},
    "IEM": {1: "Yemen League"},
    "IFA": {1: "Faroe Islands Premier League"},
    "IMA": {1: "Isle of Man Football League"},
    "IMR": {1: "Championnat de la Mauritanie"},
    "IND": {1: "Indian Super League", 2: "I-League"},
    "IRA": {1: "Persian Gulf Pro League", 2: "Azadegan League"},
    "IRL": {1: "League of Ireland Premier Division", 2: "League of Ireland First Division"},
    "IRN": {1: "Persian Gulf Pro League", 2: "Azadegan League"},
    "IRQ": {1: "Iraqi Premier League"},
    "ISA": {1: "Israeli Premier League", 2: "Israeli National League"},
    "ISL": {1: "Úrvalsdeild karla"},
    "ISR": {1: "Ligat Ha'Al", 2: "Liga Leumit"},
    "ITC": {1: "Campionato Sammarinese"},
    "IVA": {1: "Ligue 1 Ivoirienne", 2: "Ligue 2 Ivoirienne"},
    "IVB": {1: "BVI Football League"},
    "JAM": {1: "Jamaica Premier League"},
    "JOR": {1: "Jordanian Pro League"},
    "KIR": {1: "Kiribati National Championship"},
    "KOS": {1: "Football Superleague of Kosovo"},
    "KUW": {1: "Kuwait Premier League"},
    "LAO": {1: "Lao Premier League"},
    "LBN": {1: "Lebanese Premier League"},
    "LES": {1: "Lesotho Premier League"},
    "LET": {1: "Latvian Higher League", 2: "Latvian First League"},
    "LIB": {1: "Libyan Premier League"},
    "LIE": {1: "Liechtenstein Football Cup"},
    "LIT": {1: "A Lyga", 2: "I Lyga"},
    "LRI": {1: "Liberian First Division"},
    "LUX": {1: "BGL Ligue", 2: "Éirepromotioun"},
    "MAC": {1: "Liga Macaense de Futebol"},
    "MAD": {1: "THB Champions League (Madagascar)"},
    "MAL": {1: "Malaysian Super League", 2: "Malaysia Premier League"},
    "MAR": {1: "Botola Pro", 2: "Botola 2", 3: "Botola 3", 4: "Botola 4"},
    "MAU": {1: "Mauritian League"},
    "MCD": {1: "Macedonian First League", 2: "Macedonian Second League"},
    "MEX": {1: "Liga MX", 2: "Liga de Expansión MX", 3: "Liga Premier", 4: "Liga TDP"},
    "MGL": {1: "Mongolian Premier League"},
    "MIA": {1: "Myanmar National League"},
    "MLD": {1: "Maldives National Football League"},
    "MLI": {1: "Malian Première Division"},
    "MNC": {1: "Ligue 1 (Monaco)"},
    "MOC": {1: "Moçambola"},
    "MOL": {1: "Moldovan Super Liga", 2: "Divizia A"},
    "MON": {1: "MNE Prva Liga", 2: "MNE Druga Liga"},
    "MST": {1: "Montserrat Championship"},
    "MTA": {1: "Maltese Premier League", 2: "Maltese Challenge League"},
    "MTI": {1: "Championnat de la Martinique"},
    "MWI": {1: "TNM Super League (Malawi)"},
    "NAM": {1: "Namibia Premier League"},
    "NAU": {1: "Nauru Football Championship"},
    "NCA": {1: "Liga Primera de Nicaragua"},
    "NEP": {1: "Nepal Super League"},
    "NIC": {1: "Liga Primera de Nicaragua"},
    "NIG": {1: "Nigeria Professional Football League", 2: "Nigeria National League"},
    "NIR": {1: "NIFL Premiership", 2: "NIFL Championship"},
    "NOR": {1: "Eliteserien", 2: "OBOS-ligaen", 3: "PostNord-ligaen", 4: "Norsk Tipping-ligaen"},
    "NOZ": {1: "New Zealand Football Championship"},
    "OMA": {1: "Oman Professional League"},
    "PAL": {1: "West Bank Premier League"},
    "PAN": {1: "Liga Panameña de Fútbol"},
    "PAQ": {1: "Pakistan Premier League"},
    "PAR": {1: "División de Honor", 2: "División Intermedia", 3: "Primera División B", 4: "División C"},
    "PER": {1: "Liga 1", 2: "Liga 2", 3: "Copa Perú", 4: "Copa Perú Regional"},
    "PGA": {1: "Primeira Liga Timorense"},
    "PLU": {1: "Liga Panameña de Fútbol 2"},
    "PNG": {1: "Papua New Guinea National Soccer League"},
    "POL": {1: "Ekstraklasa", 2: "I Liga", 3: "II Liga", 4: "III Liga"},
    "PRI": {1: "Puerto Rico 1st Division"},
    "QUE": {1: "Kenya Premier League", 2: "Kenya National Super League"},
    "QUI": {1: "Kyrgyz Premier League"},
    "RCA": {1: "Championnat de Centrafrique"},
    "RDG": {1: "Liga Dominicana"},
    "RDO": {1: "Liga Dominicana de Fútbol"},
    "ROM": {1: "SuperLiga România", 2: "Liga II", 3: "Liga III"},
    "RTC": {1: "Czech First League", 2: "Czech National Football League"},
    "RUA": {1: "Ligue 1 du Rwanda"},
    "SAM": {1: "Samoa Premier League"},
    "SAN": {1: "Campionato Sammarinese"},
    "SCN": {1: "Saint Kitts Premier Division"},
    "SEN": {1: "Ligue 1 Sénégalaise"},
    "SER": {1: "Serbian SuperLiga", 2: "Prva Liga Srbije", 3: "Srpska Liga", 4: "Zona Liga"},
    "SEY": {1: "Seychelles Premier League"},
    "SIN": {1: "Singapore Premier League"},
    "SIR": {1: "Syrian Premier League"},
    "SLE": {1: "Sierra Leone Premier League"},
    "SME": {1: "Campionato Sammarinese"},
    "SMF": {1: "Championnat de Saint-Martin"},
    "SMH": {1: "Saint Helena Football"},
    "SOM": {1: "Somali First Division"},
    "SRI": {1: "Sri Lanka Football Premier League"},
    "STL": {1: "SLFA Premier League (St. Lucia)"},
    "STP": {1: "Campeonato de São Tomé e Príncipe"},
    "SUD": {1: "Sudanese Premier League"},
    "SUR": {1: "SVB Hoofdklasse"},
    "SUS": {1: "South Sudan Football League"},
    "SVG": {1: "SVGFF Premier Division"},
    "TAD": {1: "Tajikistan Higher League"},
    "TAI": {1: "Thai League 1", 2: "Thai League 2"},
    "TAN": {1: "Tanzanian Premier League"},
    "TAW": {1: "Taiwan Football Premier League"},
    "TCM": {1: "Turkmenistan Higher League"},
    "TML": {1: "Championnat du Togo"},
    "TON": {1: "Tonga Major League"},
    "TRT": {1: "TT Pro League"},
    "TTI": {1: "Timor-Leste Premier League"},
    "TUN": {1: "Ligue 1 Tunisienne", 2: "Ligue 2 Tunisienne"},
    "TUV": {1: "Tuvalu A-Division"},
    "UGA": {1: "Uganda Premier League"},
    "URU": {1: "Primera División", 2: "Segunda División", 3: "Primera Amateur", 4: "Segunda Amateur"},
    "UZB": {1: "Uzbekistan Super League", 2: "Uzbekistan Pro League"},
    "VAN": {1: "Vanuatu Premier League"},
    "VEN": {1: "Liga FUTVE", 2: "Liga FUTVE 2", 3: "Liga FUTVE 3", 4: "Liga FUTVE 4"},
    "VIE": {1: "V.League 1", 2: "V.League 2"},
    "ZAM": {1: "Zambia Super League", 2: "Zambia First Division"},
    "ZIM": {1: "Zimbabwe Premier Soccer League"},
}

# ═══════════════════════════════════════════════════════════
#  REAL SPONSORS PER TEAM (major European leagues)
# ═══════════════════════════════════════════════════════════

SPONSORS_EU = {
    # ── ENGLAND (Premier League) ──
    "chelsea": "Infinite Athlete",
    "liverpool_ing": "Standard Chartered",
    "machester_ing": "Snapdragon",
    "machestercity_ing": "Etihad Airways",
    "tottenhamhotspur_ing": "AIA",
    "arsenal": "Emirates",
    "astonvilla_ing": "Betano",
    "newcastle_ing": "Sela",
    "westham_eng": "Betway",
    "crystalpalace_ing": "Cinch",
    "leicestercity_ing": "FBS",
    "middlesbrough_ing": "Dunelm",
    "nottinghamforest_ing": "UNHCR",
    "brighton_ing": "American Express",
    "everton_ing": "Stake",
    "brentford_ing": "Hollywoodbets",
    "bournemouth_ing": "DuFry",
    "birmingham_ing": "Ultra White Collar Boxing",
    "blackburn_ing": "Totally Wicked",
    "bolton_ing": "Victorian Plumbing",
    # ── Championship ──
    "fulham_ing": "World Mobile",
    "wolverhampton_ing": "AstroPay",
    "southampton_ing": "Sportsbet.io",
    "derby_ing": "32Red",
    "sunderland_ing": "MansionBet",
    "leeds_ing": "BOXT",
    "burnley_ing": "W88",
    "sheffieldunited_ing": "USG",
    "watford_ing": "Stake.com",
    "hull_ing": "Donr",
    "swansea_ing": "Swansea.com",
    "cardiff_ing": "Visit Malaysia",
    "reading_ing": "Select Car Leasing",
    "coventry_ing": "Ryobi",
    "stokeCity_ing": "bet365",
    "millwall_ing": "1XBET",
    "bristol_ing": "Dunder",
    "luton_ing": "888sport",
    "wigan_ing": "DW Sports",
    "qpr_ing": "Royal Panda",
    "norwich_ing": "Lotus",
    "ipswich_ing": "Ed Sheeran",
    "preston_ing": "North End Bid",
    "plymouth_ing": "Ginsters",
    # ── SPAIN (LaLiga) ──
    "barcelona_esp": "Nike",
    "realmadrid_esp": "Emirates",
    "atleticomadrid_esp": "Riyadh Season",
    "realsociedad_esp": "Euskaltel",
    "villarreal_esp": "Joma",
    "realbetis_esp": "Caja Rural",
    "athletic_esp": "Kutxabank",
    "girona_esp": "Dahua Technology",
    "valencia_esp": "Bwin",
    "rayo_esp": "Kia",
    "osasuna_esp": "Aramark",
    "sevilla_esp": "Marathon Bet",
    "celta_esp": "Abanca",
    "mallorcareal_esp": "TUI",
    "laspalmass_esp": "Servatur",
    "getafe_esp": "Hyundai",
    "deportivoalaves_esp": "Baskonia",
    "espanyol_esp": "Riviera Maya",
    "leganes_esp": "SoloAzar",
    "real_valladolid_esp": "Kia",
    # ── LaLiga 2 ──
    "deportivolacoruna_esp": "Estrella Galicia",
    "sporting_esp": "Dsjbet",
    "elche_esp": "Visit Elche",
    "real_zaragoza_esp": "Cajalón",
    "levante_esp": "Energy Solar",
    "Racing_Santander_esp": "Hinojosa",
    "tenerife_esp": "Fred Olsen",
    "cadiz_esp": "Grupo Romero",
    "eibar_esp": "Laboral Kutxa",
    "huesca_esp": "Grupo Maz",
    # ── ITALY (Serie A) ──
    "internazionale_ita": "Betsson",
    "milan_ita": "Emirates",
    "juventus_ita": "Jeep",
    "napoli_ita": "MSC Cruises",
    "roma_ita": "Riyadh Season",
    "lazio_ita": "Binance",
    "atalanta_ita": "Gewiss",
    "fiorentina_ita": "Mediacom",
    "torino_ita": "Suzuki",
    "bologna_ita": "Illumia",
    "udinese_ita": "Bluenergy",
    "sassuolo_ita": "Mapei",
    "empoli_ita": "Computer Gross",
    "monza_ita": "Berlusconi Group",
    "genoa_ita": "Esaote",
    "lecce_ita": "Expectra",
    "cagliari_ita": "Ichnusa",
    "como_ita": "Radici Group",
    "venezia_ita": "Visit Venezia",
    "parma_ita": "Dallara",
    "hellas_ita": "Helbiz",
    "verona_ita": "Helbiz",
    "salernitana_ita": "Mary Srl",
    "sampdoria_ita": "ERG",
    "cremonese_ita": "Acciaieria Arvedi",
    "spezia_ita": "Lunigiana",
    "frosinone_ita": "Unicusano",
    "palermo_ita": "Greengen",
    "bari_ita": "Decaro Group",
    "brescia_ita": "Feralpi",
    "pisa_ita": "Cetilar",
    "modena_ita": "BPER Banca",
    "reggianamodena_ita": "BPER Banca",
    "catanzaro_ita": "Callipo",
    # ── GERMANY (Bundesliga) ──
    "bayerndemunique_ale": "Deutsche Telekom",
    "dortmund_ale": "1&1",
    "leverkusen_ale": "Barmenia",
    "rbleipzig_ale": "Red Bull",
    "stuttgart_ale": "Mercedes-Benz Bank",
    "eintrachfrankfurt_ale": "Indeed",
    "wolfsburg_ale": "Volkswagen",
    "friburgo_ale": "Schwarzwaldmilch",
    "hoffenheim_ale": "Jobrad",
    "mainz05_ale": "Kömmerling",
    "werderbremen_ale": "Wiesenhof",
    "augsburg_ale": "WWK Versicherungen",
    "union_ale": "Aroundtown",
    "gladbach_ale": "Flatex",
    "bochum_ale": "Vonovia",
    "koln_ale": "Rewe",
    "heidenheim_ale": "Hartmann",
    "darmstadt_ale": "Entega",
    "hertha_ale": "Autohero",
    "schalke04_ale": "Vivawest",
    "hamburgo_ale": "HanseMerkur",
    "nuremberg_ale": "Nürnberger Versicherung",
    "hannover96_ale": "Heinz von Heiden",
    "kaiserslautern_ale": "Dr. Theiss",
    # ── FRANCE (Ligue 1) ──
    "psg": "Qatar Airways",
    "marseille_fra": "CMA CGM",
    "monaco_fra": "Visitmonaco.com",
    "lille_fra": "Boulanger",
    "nice_fra": "Uber Eats",
    "rennes_fra": "Samsic",
    "lens_fra": "Bolloré",
    "lyon_fra": "Holtzinger",
    "strasbourg_fra": "Vinci Energies",
    "nantes_fra": "Synergie",
    "toulouse_fra": "Lidl",
    "montpellier_fra": "Nicollin",
    "brest_fra": "Cadiou",
    "reims_fra": "Socpresse",
    "lehavre_fra": "TotalEnergies",
    "clermont_fra": "Michelin",
    "lorient_fra": "Bolloré",
    "metz_fra": "Saint-Gobain",
    "auxerre_fra": "AJ Auxerre",
    "ajaccio_fra": "Corsica Linea",
    "angers_fra": "Crédit Mutuel",
    "bordeaux_fra": "Bistro Régent",
    "stetienne_fra": "Caisse d'Épargne",
    "troyes_fra": "AUBE en Champagne",
    # ── PORTUGAL (Liga Portugal) ──
    "benfica_por": "Emirates",
    "portof_por": "DragonForce",
    "sportinglisboa_por": "Macron",
    "braga_por": "Betano",
    "vitoria_por": "Betano",
    "boavista_por": "Casino do Porto",
    "maritimo_por": "Estrela",
    "portimonense_por": "Algarve Caps",
    "gildavicente_por": "Vila de Gaia",
    "pacos_por": "Efapel",
    "famalicao_por": "Cofidis",
    "estoril_por": "Casino Estoril",
    "aroucaa_por": "Vale de Cambra",
    "rio_ave_por": "Superbock",
    "moreirense_por": "Vizela",
    "vizela_por": "Vizela City",
    "chaves_por": "Flaviae",
    "casapia_por": "Casa Pia AC",
    "farense_por": "Farense",
    "estarreja_por": "Star Hotel",
    "nacional_por": "Madeira Island",
    "santaclara_por": "Santa Clara",
    # ── NETHERLANDS (Eredivisie) ──
    "ajax": "Ziggo",
    "psv_hol": "Philips",
    "feyenoord_hol": "Droomparken",
    "azalkmaar_hol": "LeasePlan",
    "twente_hol": "Grolsch",
    "utrecht_hol": "Basic-Fit",
    "vitesse_hol": "Ochama",
    "heerenveen_hol": "Maxxus",
    "groningen_hol": "Topicus",
    "sparta_hol": "Mandemakers",
    "waalwijk_hol": "Fun",
    "nijmegen_hol": "Brainwash",
    "cambuur_hol": "Abe Lenstra",
    "emmen_hol": "Bouwbedrijf Pot",
    "volendam_hol": "Volero",
    "zwolle_hol": "Beter Bed",
    "sittard_hol": "Limburg",
    "excelsior_hol": "Simpele",
    # ── TURKEY (Süper Lig) ──
    "galatasaray_tur": "Sixt",
    "fenerbahce_tur": "Puma",
    "besiktas_tur": "Beko",
    "trabzonspor_tur": "Papara",
    "basaksehir_tur": "Trendyol",
    "kasimpasa_tur": "Anadolu Efes",
    "konyaspor_tur": "Torku",
    "alanyaspor_tur": "Corendon",
    "antalyaspor_tur": "Regnum",
    "sivasspor_tur": "Yıldız Holding",
    "rizespor_tur": "Çaykur",
    "gaziantep_tur": "Gaziantep BB",
    "kayserispor_tur": "Erciyes",
    "giresunspor_tur": "Giresun BB",
    "hatayspor_tur": "Hatay BB",
    "adanademirspor_tur": "Adana BB",
    "sakaryaspor_tur": "Sakarya BB",
    # ── SCOTLAND ──
    "celtic_esc": "Dafabet",
    "rangers_esc": "32Red",
    "aberdeen_esc": "Saltire Energy",
    "hibernian_esc": "Mowi",
    "hearts_esc": "Bairds Malt",
    "dundeeunited_esc": "GA Engineering",
    "motherwell_esc": "Sparrows",
    "stmirren_esc": "Talk360",
    "kilmarnock_esc": "QTS",
    "livingston_esc": "Tony Macaroni",
    "rosscounty_esc": "MFR",
    "stjohnstone_esc": "Nairn's",
    # ── ARGENTINA ──
    "bocajuniors_arg": "Binance",
    "riverplate_arg": "Codere",
    "racingclub_arg": "BC.GAME",
    "sanlorenzo_arg": "Betway",
    "independiente_arg": "Betway",
    "velez_arg": "Rushbet",
    "estudiantes_arg": "Tecno",
    "rosariocentral_arg": "Te Apuesto",
    "newells_arg": "Colón",
    "talleres_arg": "Iveco",
    "defensa_arg": "Manaos",
    "lanus_arg": "Quilmes",
    "banfield_arg": "Codere",
    "godoycruz_arg": "RPM",
    "argentinos_arg": "Argentinos Jrs",
    "colon_arg": "Sabalero",
    "atleticotucuman_arg": "NOA",
    "uniondesantafe_arg": "Te Apuesto",
    "huracan_arg": "1Win",
    "sarmiento_arg": "Casino Junín",
    "centralcordoba_arg": "Santiago City",
    "platense_arg": "Binance",
    "belgrano_arg": "Te Apuesto",
    "tigre_arg": "1Win",
    "gimnasia_arg": "Casino Club",
    "barracascentral_arg": "AFA",
    "arsenal_arg": "Arsenal de Sarandí",
    "riestra_arg": "Riestra de Fútbol",
    # ── RUSSIA ──
    "zenit_rus": "Gazprom",
    "cska_rus": "VTB Bank",
    "spartak_rus": "Lukoil",
    "lokomotiv_rus": "Russian Railways",
    "dinamo_rus": "VTB",
    "krasnodar_rus": "Magnit",
    "rubin_kazan_rus": "Tatneft",
    "rostov_rus": "Agrokom",
    # ── SWITZERLAND ──
    "youngboys_sui": "Swisscom",
    "zurich_sui": "UPC",
    "basel_sui": "Baloise",
    "servette_sui": "Rolex",
    "lugano_sui": "Swiss Financial",
    "stgallen_sui": "Helvetia",
    "luzern_sui": "Swiss Life",
    "sion_sui": "Constantin",
}

SPONSORS_BR = {
    # ── Série C ──
    "remo_bra": "Banpará",
    "tombense_bra": "Tombos Online",
    "londrina_bra": "Unifil",
    "figueirense_bra": "Porto Belo",
    "nautico_bra": "Toritama",
    "csa_bra": "Maceió CVB",
    "sampaio_bra": "São Luís CVB",
    "saobernardo_bra": "USIMINAS",
    "abcnatal_bra": "Natal CVB",
    "confianca_bra": "Sergipe CVB",
    "floresta_bra": "Fortaleza CVB",
    "ituano_bra": "Jundiaprev",
    "pontepreta_bra": "Poty",
    "brusque_bra": "Havan",
    "guarani_bra": "Gol Finance",
    "madureira_bra": "Magalu",
    "brasiliense_bra": "Brasília CVB",
    "santacruz_bra": "Caxangá",
    "americanrn_bra": "Natal CVB",
    "campinense_bra": "Campina Grande CVB",
    # ── Série D (major) ──
    "bangu_bra": "Rio CVB",
    "caxias_bra": "Serra Gaúcha",
    "ypiranga_bra": "Erechim",
    "boaesporte_bra": "Varginha CVB",
    "ipatinga_bra": "Usiminas",
    "icasa_bra": "Juazeiro CVB",
    "gama_bra": "Brasília CVB",
    "vila_nova_bra": "Goiânia CVB",
    "anapolina_bra": "Anápolis CVB",
    "desportiva_bra": "Vitória CVB",
}


def update_leagues():
    path = os.path.join(SEEDS, "leagues.json")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    for code, divs in data.items():
        for d in divs:
            # Add licenciada flag
            d["licenciada"] = True

            # Update generic names
            nome = d.get("nome", "")
            div_num = d.get("divisao", 1)
            if code in REAL_LEAGUE_NAMES and div_num in REAL_LEAGUE_NAMES[code]:
                real = REAL_LEAGUE_NAMES[code][div_num]
                if not nome or "Divisão" in nome or nome.startswith("Div "):
                    d["nome"] = real

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {len(data)} countries in leagues.json")


def update_sponsors_eu():
    path = os.path.join(SEEDS, "teams_eu.json")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    for country_code, country_data in data.items():
        if "divisoes" not in country_data:
            continue
        for div_key, teams in country_data["divisoes"].items():
            for team in teams:
                fk = team.get("file_key", "")
                if fk in SPONSORS_EU:
                    team["patrocinador"] = SPONSORS_EU[fk]
                    updated += 1

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {updated} EU team sponsors")


def update_sponsors_br():
    path = os.path.join(SEEDS, "teams_br.json")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    for division, teams in data.items():
        for team in teams:
            fk = team.get("file_key", "")
            if fk in SPONSORS_BR and not team.get("patrocinador"):
                team["patrocinador"] = SPONSORS_BR[fk]
                updated += 1

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {updated} BR team sponsors")


if __name__ == "__main__":
    update_leagues()
    update_sponsors_eu()
    update_sponsors_br()
    print("Done!")
